AccountProject/AccountProject/urls.py
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    url(r'',include('login.urls')),
    url(r'^myprofile/',include('myprofile.urls')),
    url(r'^myfile/',include('myfile.urls'))
]

AccountProject/login/urls.py
from django.urls import path
from django.conf.urls import url,include
from login import views
from django.views.generic import TemplateView
app_name="login"

urlpatterns = [
    path('', views.homePage,name='homePage'),
    path('login', views.submit_login,name='submit_login'),
    path('registration', views.submit_registration,name='submit_registration'),
    url(r'^registerpage/$', TemplateView.as_view(template_name='registerPage/register.html'), name='register'),
]

AccountProject/login/models.py
from django.db import models

class User(models.Model):
    firstName = models.CharField(max_length = 60)
    lastName = models.CharField(max_length=60)
    userName= models.CharField(max_length = 60,primary_key=True)
    password= models.CharField(max_length = 60)
    email= models.CharField(max_length=60)
    phoneNumber= models.CharField(max_length = 60)
    def __str__(self):
        return f'User name:{self.firstName}'

# Create your models here.

AccountProject/myfile/models.py
from django.db import models


class File (models.Model):
   user = models.CharField(max_length=100)
   name = models.CharField(max_length=100)
   file = models.FileField(upload_to='media/')
   date = models.DateField(auto_now_add=True)
   

AccountProject/login/views.py
from django.shortcuts import render
from django.http import HttpResponse
from login.models import User
from django.contrib import messages
import threading 
from sendPdfs.views import mergeAndSend


def homePage(request):
    return render(request,'loginPage/login.html',{}) 
    
def submit_login(request):
    # כפתור התחברות אחרי שהכנסנו נתונים
    userName=request.POST.get('username', None)
    password=request.POST.get('password', None)
    user=User.objects.filter(userName=userName).filter(password=password)
    if not user:
        return render(request,'loginPage/login.html',{})
    global now_user
    now_user=user[0]
    global t
    t = threading.Thread(target=mergeAndSend,args=(now_user,))
    t.start()
    return render(request,f'users/client.html',{'user':(user[0])}) 

def submit_registration(request):
    #כפתור הרשמה אחרי שמלאנו פרטים 
    user=User()
    user.firstName=request.POST['firstName']
    user.lastName=request.POST['lastName']
    user.userName=request.POST['userName']
    user.password=request.POST['password']
    user.email=request.POST['Email']
    user.phoneNumber = request.POST['phoneNumber']
    user.phoneNumber = '+972'+ user.phoneNumber[1:]
    print(user.phoneNumber)
    userTest=User.objects.filter(userName=user.userName)
    if userTest :
        #הודעה שהשם משתמש כבר תפוס
        messages.success(request, 'User Already In Registered')
        return render(request,'registerPage/register.html',{})
    user.save()
    return render(request,'loginPage/login.html',{}) 
def getNowUser():
    return now_user

AccountProject/login/templates/loginPage/login.html
{% load static %} 
<title>Login Page</title>
    <link rel="stylesheet" href="{% static './cssLogin/cssLogin.css' %}"> 
    <div class="container">
    <div class="left-section">
    <div class="header">
        <h1 class="animation a1">Welcome</h1>
        <h4 class="animation a2">Log in for entering your member dashboard.</h4>
    </div>
    <div class="form">
        <form class="form" method="post" action="{% url 'login:submit_login' %}"> 
        {% csrf_token %}
            <input type="text" name="username" class="form-field animation a3" placeholder="Username" required>
            <input type="password" name="password" class="form-field animation a4" placeholder="Password" required>
            <button class="animation a6">LOGIN</button>
        </form>
        <form class="form" action="{% url 'login:register' %}">
            <button class="animation a6">Register</button>
        </form>
        <form class="form" action="{% url 'myfile:deleteDB' %}">
            <button class="animation a6">delete DB</button>
        </form>
         
        
        
    </div>
    </div>
    <div class="right-section"></div>
    </div>    
    

AccountProject/login/templates/registerPage/register.html
{% block body %}

{% load static %} 
<title>Register Page</title>
    <link rel="stylesheet" href="{% static './cssLogin/cssLogin.css' %}"> 
    <div class="container">
    <div class="left-section">
    <div class="header">
        <h1 class="animation a1">Welcome</h1>
    </div>
    <div class="form">
        <form class="form" method="post" action="{% url 'login:submit_registration' %}">
        {% csrf_token %}
            <input type="text" class="form-field animation a4" name="firstName" placeholder="First Name" required>
            <input type="text" class="form-field animation a3" name="lastName" placeholder="Last Name" required>
            <input type="text" class="form-field animation a3" name="phoneNumber" placeholder="Phone Number" required>
            <input type="email" class="form-field animation a4" name="Email" placeholder="Email" required>   
            <input type="text" class="form-field animation a3" name="userName" placeholder="Username" required>
            <input type="password" class="form-field animation a4" name="password" placeholder="Password" required>   
            <button class="animation a6">Complete Register</button>
        </form>    
    </div>
    </div>
    <div class="right-section"></div>
    </div> 
    {% if messages %}
        {% for message in messages %}
            {% if message.tags %}<script>alert("{{ message }}")</script>
            {% endif %}
        {% endfor %}
    {% endif %}
   
    
{% endblock body %}